name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request: {}

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      dockerfile_any_changed: ${{ steps.changed-files-yaml.outputs.dockerfile_any_changed }}
      dockerfile_all_changed_files: ${{ steps.changed-files-yaml.outputs.dockerfile_all_changed_files }}
    steps: 
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    - name: Get all Dockerfile files that have changed
      id: changed-files-yaml
      uses: tj-actions/changed-files@v37
      with:
        files_yaml: |
          dockerfile:
            - '**/Dockerfile'
  build:
    needs: diff
    runs-on: ubuntu-latest
    if: needs.diff.outputs.dockerfile_any_changed == 'true'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.2.0
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.9.1
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push the Docker image
      run: |
        for file in ${{ needs.diff.outputs.dockerfile_all_changed_files  }}; do
          dir=$(dirname $file)
          IMAGE=$(dirname $dir)
          TAG=$(basename $dir)
          echo "building image $IMAGE"
          docker build ${IMAGE} --file ${file} --tag kuromesi/${IMAGE}:${TAG}
          docker push kuromesi/${IMAGE}:${TAG}
        done
